# -*- coding: utf-8 -*-
"""Copy of Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Lb8iD2AMXPVVREzYfB8Obsff6orieq-

**GRADUATE ROTATIONAL INTERNSHIP PROGRAM @THE SPARKS FOUNDATION**

By:Keerthi krishna B

**Task 1:Object Detection/Optical Character Recognition**

Description:Character detector which extracts printed or handwritten text from an image or video

Installation of easyocr
"""

!pip install easyocr

"""Importing modules"""

import easyocr
import cv2
import matplotlib.pyplot as plt
import numpy as np

"""Reading text from images"""

img_path="text.jpg"
img=cv2.imread(img_path)
reader=easyocr.Reader(["en"],gpu=True)
result=reader.readtext(img_path)
plt.imshow(img)
plt.show()
print(result)

"""Showing the results"""

for detection in result:
  top_left=tuple([int(val) for val in detection[0][0]])
  bottom_right=tuple([int(val) for val in detection[0][2]])
  text=detection[1]
  font=cv2.FONT_HERSHEY_COMPLEX
  img=cv2.rectangle(img,top_left,bottom_right,(0,255,0),5)
  img=cv2.putText(img,text,top_left,font,1.2,(0,0,0),2,cv2.LINE_AA)
plt.imshow(img)
plt.show()